image:
  repository: yossisht11/digbackend
  tag: "0.0.2"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5000
resources: {}
postgres:
  dbName: "dig"
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  mountPath: /var/lib/postgresql/data