replicaCount: 1
image:
  repository: yossisht11/digfrontend
  pullPolicy: IfNotPresent
  tag: "0.0.5"
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: digforntend.local
      paths: []
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: []
postgres:
  dbName: "dig"
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /var/lib/postgresql/data
# postgresql:
#   enabled: true
#   image: postgres:latest
#   persistence:
#     enabled: true
#     size: 1Gi
#     storageClass: ""
