# charts/postgresql-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql-chart.fullname" . }}
  labels:
    {{- include "postgresql-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgresql-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgresql-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgresql
          image: bitnami/postgresql:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POST_DB_NAME
              value: "{{ .Values.postgresql.postgres.dbName }}"
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POST_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc
