apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-chart.fullname" . }}
  labels:
    {{- include "postgresql-chart.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    {{- include "postgresql-chart.selectorLabels" . | nindent 4 }}

