apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "digfrontend.fullname" . }}
  labels:
    {{- include "digfrontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "digfrontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "digfrontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data-volume
              mountPath: {{ .Values.persistence.mountPath }}
          env:
            - name: POST_DB_NAME
              value: "{{ .Values.postgres.dbName }}"
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POST_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "digfrontend.fullname" . }}-pvc
