apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "digbackend.fullname" . }}
  labels:
    {{- include "digbackend.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "digbackend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "digbackend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: upload-volume
              mountPath: /app/data/uploads
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
          env:
            - name: POST_DB_NAME
              value: "{{ .Values.postgres.dbName }}"
            - name: POST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POST_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
      volumes:
        - name: upload-volume
          emptyDir: {}
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc
