apiVersion: v1
kind: Service
metadata:
  name: {{ include "  repository: digbackend.fullname" . }}
  labels:
    {{- include "  repository: digbackend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
  selector:
    {{- include "  repository: digbackend.selectorLabels" . | nindent 4 }}

